# ======================
# Server
# ======================
port: "8080"

# ======================
# Databases
# ======================
mongo_uri: mongodb://localhost:27017/wallet

# ======================
# Ethereum chain config
# ======================
eth:
  rpc: http://127.0.0.1:8545
  chain_id: 31337
  main_net: false
