# ======================
# Server
# ======================
port: "8080"

# ======================
# Databases
# ======================
mongo_uri: mongodb://localhost:27017/wallet

# ======================
# Ethereum chain config
# ======================
eth:
  rpc: https://sepolia.infura.io/v3/
  test_token: xxx
  chain_id: 11155111
  main_net: false
